parameters:
  toxenvs: []
  os: linux
  architecture: x64
  coverage: true
  wheel_tags: false
  additional_variables: {}
  pre_test: []
  name_postfix: ''

jobs:
- job: ${{ format('tox_{0}{1}', parameters.os, parameters.name_postfix) }}
  strategy:
    matrix:
      ${{ each env in parameters.toxenvs }}:
        ${{ env }}:
          TOXENV: ${{ env }}
          ${{ if or(eq(env, 'py26'), startsWith(env, 'py26-')) }}:
            py: '3.7'
            ispy26: true
          ${{ if or(eq(env, 'py27'), startsWith(env, 'py27-')) }}:
            py: '2.7'
          ${{ if or(eq(env, 'py34'), startsWith(env, 'py34-')) }}:
            py: '3.4'
          ${{ if or(eq(env, 'py35'), startsWith(env, 'py35-')) }}:
            py: '3.5'
          ${{ if or(eq(env, 'py36'), startsWith(env, 'py36-')) }}:
            py: '3.6'
          ${{ if or(eq(env, 'py37'), startsWith(env, 'py37-')) }}:
            py: '3.7'
          ${{ if or(eq(env, 'pypy'), startsWith(env, 'pypy-')) }}:
            py: 'pypy2'
          ${{ if or(eq(env, 'pypy3'), startsWith(env, 'pypy3-')) }}:
            py: 'pypy3'
          # we'll run tox using this on py38
          ${{ if or(eq(env, 'py38'), startsWith(env, 'py38-')) }}:
            py: '3.7'
            ispy38: true

  pool:
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: ubuntu-16.04
    ${{ if eq(parameters.os, 'windows') }}:
      vmImage: vs2017-win2016
    ${{ if eq(parameters.os, 'osx') }}:
      vmImage: macOS-10.13

  variables:
    ${{ if eq(parameters.os, 'windows') }}:
      bindir: Scripts
    ${{ if ne(parameters.os, 'windows') }}:
      bindir: bin
    ${{ insert }}: ${{ parameters.additional_variables }}

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(py)
      architecture: ${{ parameters.architecture }}

  - script: |
      sudo add-apt-repository ppa:deadsnakes
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends python3.8-dev python3.8-distutils
    condition: variables.ispy38
    displayName: install python 3.8

  - script: |
      sudo add-apt-repository ppa:deadsnakes
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends python2.6-dev
    condition: variables.ispy26
    displayName: install python 2.6

  - ${{ parameters.pre_test }}

  - script: python -m pip install --upgrade tox setuptools virtualenv
    displayName: install tox
  - script: tox
    displayName: run tox

  - ${{ if eq(parameters.coverage, true) }}:
    - bash: .tox/$(TOXENV)/$(bindir)/coverage xml -o coverage.xml
      displayName: generate coverage xml
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: cobertura
        summaryFileLocation: coverage.xml
      displayName: publish coverage artifact

  - ${{ if eq(parameters.wheel_tags, true) }}:
    - bash: .tox/$(TOXENV)/$(bindir)/pip wheel --no-deps . -w wheels
      displayName: build wheel
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    - task: PublishBuildArtifacts@1
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      inputs:
        pathToPublish: wheels
        artifactName: wheel_${{ parameters.os }}_$(TOXENV)${{ parameters.name_postfix }}
      displayName: publish wheel artifact
