parameters:
  ruby: '>= 2.4'
  python: '3.8'

jobs:
- job: precommit
  pool:
    vmImage: ubuntu-18.04
  variables:
    PRE_COMMIT_HOME: $(Pipeline.Workspace)/pre-commit-cache

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.python }}
  - task: UseRubyVersion@0
    inputs:
      versionSpec: ${{ parameters.ruby }}

  - script: |
      echo "##vso[task.setvariable variable=PY]$(python -VV)"
      echo "##vso[task.setvariable variable=RB]$(ruby -v)"
    displayName: set version variables

  - task: CacheBeta@0
    inputs:
      key: pre-commit | "4" | .pre-commit-config.yaml | "$(PY)" | "$(RB)"
      path: $(PRE_COMMIT_HOME)

  - script: python -m pip install --upgrade pre-commit
    displayName: install pre-commit
  - script: pre-commit run --all-files --show-diff-on-failure --color=always
    displayName: run pre-commit
